body:
  - type: input
    id: announcement_title
    attributes:
      label: "Announcement Title"
      description: "Give the announcement a meaningful title."
    validations:
      required: true
  - type: textarea
    id: announcement_body
    attributes:
      label: "Announcement Body"
      description: "Announcement message goes here."
    validations:
      required: true
